name = "team8-backend"
main = "backend/src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "team8-db"
database_id = "to-be-replaced-with-real-id"
preview_database_id = "DB"
